name: velocity_x_agent_builder_repo

packages:
  - .


scripts:
  update-goldens: melos exec -- flutter test --update-goldens
  test: melos exec -- flutter test --coverage
  analyze: melos exec -- flutter analyze
  format: melos exec -- dart format .
  build: melos exec -- protoc --dart_out=grpc:lib -Ilib lib/data/user/user.proto
  all: melos test && melos analyze && melos format
  coverage: melos exec -- flutter test --coverage
  # && lcov --extract coverage/lcov.info "./lib/user.pb.dart" --output-file coverage/user_lcov.info 
  # && awk -F":" '/LF:/ {total=$2} /LH:/ {hit=$2} END {print hit/total}' coverage/user_lcov.info > coverage/coverage.txt



  # awk -F":" '/LF:/ {total=$2} /LH:/ {hit=$2} END {print hit/total}' coverage/lcov.info > coverage/coverage.txt
  # flutter test test.dart --coverage && lcov --remove coverage/lcov.info  -o coverage/lcov.info