name: ideal_app_workspace

packages:
  - .

scripts:
  update-goldens: melos exec -- flutter test --update-goldens
  
  test: melos exec -- flutter test --coverage

  analyze: melos exec -- flutter analyze

  format: melos exec -- dart format .

  build: melos exec -- dart run build_runner build --delete-conflicting-outputs

  fix: melos exec -- dart fix --apply

  update-version: melos version --all --yes --message="bump version" -V ideal_app:minor