name: velocity_x_agent_builder_repo

packages:
  - .

scripts:
  update-goldens: melos exec -- flutter test --update-goldens
  test: melos exec -- flutter test --coverage
  analyze: melos exec -- flutter analyze
  format: melos exec -- dart format .
  build: melos exec -- dart run build_runner build
  all: melos bs && melos build && melos analyze && melos format && melos test