name: velocity_x_agent_builder_repo

packages:
  - packages/**
  - app


scripts:
  update-goldens: melos exec -- flutter test --update-goldens
  test: melos exec -- flutter test
  analyze: melos exec -- flutter analyze
  format: melos exec -- dart format .
  all: melos test && melos analyze && melos format