name: vx_agent_builder
version: 0.0.1
description: A velocity x agent builder package.
publish_to: 'none'

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  velocity_x: ^4.1.2
  vxstate: ^2.3.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  json_serializable: ^6.7.1
  melos: ^4.0.0
  mockito: ^5.4.4
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

