name: user_data
description: User data package
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  protobuf: ^3.1.0

dev_dependencies:
  mocktail: ^1.0.0
  protoc_plugin: ^21.1.2
  test: ^1.19.2
  very_good_analysis: ^5.1.0

