name: Test Example App

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: 'test-example-app'

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        cache: true
        cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
    - run: dart pub global activate melos
    
    - name: Run Tests
      run: melos bs && melos update-goldens

    - name: Push new goldens
      run: |
        git config --global user.email "vx_example@bot.com"
        git config --global user.name "vx_example_bot"
        git add .
        git commit -m "Update goldens"
        git push
